# Generated by Django 4.2.4 on 2023-08-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='Name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='Address',
        ),
        migrations.AddField(
            model_name='bloguser',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
