# Generated by Django 4.2.4 on 2023-08-15 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AEA', '0002_rename_name_bloguser_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hirer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobdescription', models.CharField(max_length=255)),
                ('jobtitle', models.CharField(max_length=255)),
                ('jobOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AEA.hirer')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
