# Generated by Django 4.2.4 on 2023-08-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEA', '0003_freelancer_hirer_job_delete_bloguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='firstname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='lastname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='hirer',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hirer',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hirer',
            name='firstname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='hirer',
            name='lastname',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
