# Generated by Django 4.2.4 on 2023-08-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEA', '0004_freelancer_age_freelancer_email_freelancer_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('firstname', models.CharField(max_length=25, null=True)),
                ('lastname', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='hirer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='hirer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hirer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='hirer',
            name='lastname',
        ),
    ]
