# Generated by Django 4.2.4 on 2023-08-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AEA', '0005_bloguser_remove_freelancer_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogUser',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='jobtitle',
            new_name='jobTitle',
        ),
    ]
