# Generated by Django 4.2.4 on 2023-08-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_owners_username',
            new_name='postownersusername',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='posttitle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_content',
        ),
        migrations.AddField(
            model_name='post',
            name='postcontent',
            field=models.CharField(default='Default Content', max_length=1500),
        ),
    ]
