# Generated by Django 4.2.4 on 2023-08-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_post_owners_username_post_postownersusername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postownersusername',
        ),
        migrations.AddField(
            model_name='post',
            name='post_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postcontent',
            field=models.TextField(max_length=1500),
        ),
    ]
