# Generated by Django 4.2.4 on 2023-08-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_post_post_owner_alter_user_age_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
    ]
